name: flutter_boilerplate
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  dio: ^5.0.0
  internet_connection_checker: ^1.0.0
  dartz: ^0.10.1
  equatable: ^2.0.0
  json_annotation: ^4.8.1
  injectable: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.7
  auto_route: ^7.8.4
  hydrated_bloc: ^9.1.4
  flex_color_scheme: ^7.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  isar_generator: ^3.1.0+1
  auto_route_generator: ^7.3.2
  analyzer: ^5.13.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
